repos:
-   repo: https://github.com/mgedmin/check-python-versions
    rev: 0.17.0
    hooks:
    -   id: check-python-versions
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: debug-statements
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3.9
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-click==0.3.1
        - flake8-bugbear==20.1.4
-   repo: https://github.com/PyCQA/isort.git
    rev: 5.6.4
    hooks:
    -   id: isort
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        args:
        - --skip
        - B101
-   repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 0.5.0
    hooks:
    -   id: tox-ini-fmt
